
jvmOptions:
  - -Xms3600m
  - -Xmx3600m
  - -Xss256k
  - -XX:+UseG1GC
  - -XX:+PrintGC
  - -XX:+PrintGCDateStamps
  - -XX:-PrintGCDetails
  - -XX:MaxGCPauseMillis=200
  - -XX:G1ReservePercent=20
  - -Xloggc:$logdir/$serviceName/gc.log
  - -XX:+HeapDumpOnOutOfMemoryError
  - -XX:HeapDumpPath=$logdir/$serviceName
  - -XX:+UseGCLogFileRotation
  - -XX:NumberOfGCLogFiles=5
  - -XX:GCLogFileSize=2M
