#spring.profiles.active: @env@

# mysql
#db:
#  name: jvwa
#  db.host=localhost
#  db.port=3306
#  spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#  spring.datasource.url=jdbc.mysql://${db.host}:${db.port}/${db.name}?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false&amp;serverTimezone=GMT
#  spring.datasource.username=root
#  spring.datasource.password=root

##数据库配置 spring:
#datasource.url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&useSSL=true
#username: root
#password: rootroot
#driver-class-name: com.mysql.cj.jdbc.Driver   mybatis:
#mapper-locations: classpath:com/demo/mapper/*.xml
#type-aliases-package: com.demo.entity
## 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
#configuration.map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jvwa?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      min-idle: 8
      allow: 127.0.0.1
      deny: 192.168.0.114
      loginUsername: yeshaoting
      loginPassword: admin#1a#9z
      resetEnable: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#pagehelper:
#  reasonable: true
#  helper-dialect: mysql

#spring:
#  datasource:
#  # 配置数据源类型
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/jvwa?useUnicode=true&characterEncoding=UTF-8
#  username: root
#  password: root
#  # 初始化，最小，最大连接数
#  initialSize: 3
#  minidle: 3
#  maxActive: 18
#  # 获取数据库连接等待的超时时间
#  maxWait: 60000
#  # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
#  timeBetweenEvictionRunsMillis: 60000
#  validationQuery: SELECT 1 FROM dual
#  # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
#  filters: stat,wall,log4j