
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jvwa?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      min-idle: 8
      allow: 127.0.0.1
      deny: 192.168.0.114
      loginUsername: yeshaoting
      loginPassword: admin#1a#9z
      resetEnable: false
