server:
  host: localhost
  port: 8080
  context: ''
  session.timeout: 10080
  servlet:
    context-path: /
  jetty:
    max-http-form-post-size: 52428800
    threads:
      acceptors: 120
      selectors: 4

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  resources:
    static-locations: /resources/


base_url: http://${server.host}:${server.port}
server_url: ${base_url}
index_url: ${server_url}/index
resources_path: ${server_url}/resources
styles_path: ${resources_path}/css
images_path: ${resources_path}/img
scripts_path: ${resources_path}/js
resources_version: 1.0.0


file:
  upload:
    max_size: 52428800

max_stage: 8

mapper.identity: MYSQL
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


